name: expense_tracker_app
description: A Flutter app for tracking expenses.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.6
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.1.5
  provider: ^6.1.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
